export enum REQUEST_ACTIONS {
  CREATE_USER = "CREATE_USER",
  ADD_USER_INFO = "ADD_USER_INFO",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  GET_USER_INFO = "GET_USER_INFO",
  UPDATE_USER_INFO = "UPDATE_USER_INFO",
  GET_ALL_USER_POSTS = "GET_ALL_USER_POSTS",
  GET_POST = "GET_POST",
  RESET_PASSWORD = "RESET_PASSWORD",
}
