export enum REQUEST_ACTIONS {
  CREATE_USER = "CREATE_USER",
  ADD_USER_INFO = "ADD_USER_INFO",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  GET_USER_INFO = "GET_USER_INFO",
  UPDATE_USER_INFO = "UPDATE_USER_INFO",
}
